// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeItemStorageServer is an autogenerated mock type for the UnsafeItemStorageServer type
type UnsafeItemStorageServer struct {
	mock.Mock
}

// mustEmbedUnimplementedItemStorageServer provides a mock function with given fields:
func (_m *UnsafeItemStorageServer) mustEmbedUnimplementedItemStorageServer() {
	_m.Called()
}
