// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package test_task

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ItemStorageClient is the client API for ItemStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ItemStorageClient interface {
	AddNewItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*ItemID, error)
	GetAllItems(ctx context.Context, in *NoneObjectRequest, opts ...grpc.CallOption) (*EncodeItemResponse, error)
	GetItem(ctx context.Context, in *ItemID, opts ...grpc.CallOption) (*EncodeItemResponse, error)
	DeleteItem(ctx context.Context, in *ItemID, opts ...grpc.CallOption) (*NoneObjectResp, error)
	UpdateItem(ctx context.Context, in *ItemID, opts ...grpc.CallOption) (*EncodeItemResponse, error)
}

type itemStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewItemStorageClient(cc grpc.ClientConnInterface) ItemStorageClient {
	return &itemStorageClient{cc}
}

func (c *itemStorageClient) AddNewItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*ItemID, error) {
	out := new(ItemID)
	err := c.cc.Invoke(ctx, "/item.ItemStorage/AddNewItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemStorageClient) GetAllItems(ctx context.Context, in *NoneObjectRequest, opts ...grpc.CallOption) (*EncodeItemResponse, error) {
	out := new(EncodeItemResponse)
	err := c.cc.Invoke(ctx, "/item.ItemStorage/GetAllItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemStorageClient) GetItem(ctx context.Context, in *ItemID, opts ...grpc.CallOption) (*EncodeItemResponse, error) {
	out := new(EncodeItemResponse)
	err := c.cc.Invoke(ctx, "/item.ItemStorage/GetItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemStorageClient) DeleteItem(ctx context.Context, in *ItemID, opts ...grpc.CallOption) (*NoneObjectResp, error) {
	out := new(NoneObjectResp)
	err := c.cc.Invoke(ctx, "/item.ItemStorage/DeleteItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemStorageClient) UpdateItem(ctx context.Context, in *ItemID, opts ...grpc.CallOption) (*EncodeItemResponse, error) {
	out := new(EncodeItemResponse)
	err := c.cc.Invoke(ctx, "/item.ItemStorage/UpdateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemStorageServer is the server API for ItemStorage service.
// All implementations must embed UnimplementedItemStorageServer
// for forward compatibility
type ItemStorageServer interface {
	AddNewItem(context.Context, *Item) (*ItemID, error)
	GetAllItems(context.Context, *NoneObjectRequest) (*EncodeItemResponse, error)
	GetItem(context.Context, *ItemID) (*EncodeItemResponse, error)
	DeleteItem(context.Context, *ItemID) (*NoneObjectResp, error)
	UpdateItem(context.Context, *ItemID) (*EncodeItemResponse, error)
	mustEmbedUnimplementedItemStorageServer()
}

// UnimplementedItemStorageServer must be embedded to have forward compatible implementations.
type UnimplementedItemStorageServer struct {
}

func (UnimplementedItemStorageServer) AddNewItem(context.Context, *Item) (*ItemID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNewItem not implemented")
}
func (UnimplementedItemStorageServer) GetAllItems(context.Context, *NoneObjectRequest) (*EncodeItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllItems not implemented")
}
func (UnimplementedItemStorageServer) GetItem(context.Context, *ItemID) (*EncodeItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedItemStorageServer) DeleteItem(context.Context, *ItemID) (*NoneObjectResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteItem not implemented")
}
func (UnimplementedItemStorageServer) UpdateItem(context.Context, *ItemID) (*EncodeItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateItem not implemented")
}
func (UnimplementedItemStorageServer) mustEmbedUnimplementedItemStorageServer() {}

// UnsafeItemStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemStorageServer will
// result in compilation errors.
type UnsafeItemStorageServer interface {
	mustEmbedUnimplementedItemStorageServer()
}

func RegisterItemStorageServer(s grpc.ServiceRegistrar, srv ItemStorageServer) {
	s.RegisterService(&ItemStorage_ServiceDesc, srv)
}

func _ItemStorage_AddNewItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemStorageServer).AddNewItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemStorage/AddNewItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemStorageServer).AddNewItem(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemStorage_GetAllItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoneObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemStorageServer).GetAllItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemStorage/GetAllItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemStorageServer).GetAllItems(ctx, req.(*NoneObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemStorage_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemStorageServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemStorage/GetItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemStorageServer).GetItem(ctx, req.(*ItemID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemStorage_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemStorageServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemStorage/DeleteItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemStorageServer).DeleteItem(ctx, req.(*ItemID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemStorage_UpdateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemStorageServer).UpdateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemStorage/UpdateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemStorageServer).UpdateItem(ctx, req.(*ItemID))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemStorage_ServiceDesc is the grpc.ServiceDesc for ItemStorage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemStorage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "item.ItemStorage",
	HandlerType: (*ItemStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNewItem",
			Handler:    _ItemStorage_AddNewItem_Handler,
		},
		{
			MethodName: "GetAllItems",
			Handler:    _ItemStorage_GetAllItems_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _ItemStorage_GetItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _ItemStorage_DeleteItem_Handler,
		},
		{
			MethodName: "UpdateItem",
			Handler:    _ItemStorage_UpdateItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item.proto",
}
